name: Label & comment issues

on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.action === 'opened' || context.payload.action === 'reopened') {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["issue", "fix"]
              })
            }

      # This step should only comment when the issue is opened or reopened.
      - name: Comment on new issue
        if: github.event.action == 'opened' || github.event.action == 'reopened' # This condition ensures that the comment only happens when the issue is opened or reopened.
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

  comment_on_close:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on closed issue
        if: github.event.action == 'closed'  # This condition ensures that the comment happens only when the issue is closed.
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The issue is now resolved. Thanks for your patience!

  welcome_first_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the first PR
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            if (prs.data.length === 1) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "🎉 Congratulations on opening your first pull request! We appreciate your contribution."
              });
            }
